# Generated by Django 2.2.2 on 2021-08-10 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0003_user_paper_answer_is_true'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_task_answer',
            name='task_record',
        ),
        migrations.AddField(
            model_name='task_record',
            name='user_task_answer',
            field=models.ManyToManyField(to='exam.User_Task_Answer'),
        ),
    ]
