# Generated by Django 2.2.2 on 2021-08-12 19:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0008_dynamicmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='course_brief',
            field=models.TextField(blank=True, max_length=2048, null=True, verbose_name='详情介绍'),
        ),
        migrations.AddField(
            model_name='course',
            name='course_pub_date',
            field=models.DateField(auto_now_add=True, null=True, verbose_name='发布日期'),
        ),
        migrations.AddField(
            model_name='course',
            name='course_sections',
            field=models.IntegerField(default=0, null=True, verbose_name='总章节'),
        ),
        migrations.AddField(
            model_name='course',
            name='course_students',
            field=models.IntegerField(default=0, null=True, verbose_name='学习人数'),
        ),
        migrations.AddField(
            model_name='course',
            name='course_user',
            field=models.ManyToManyField(to='exam.User'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_vip',
            field=models.BooleanField(default=False, verbose_name='是否会员'),
        ),
        migrations.AlterField(
            model_name='course',
            name='course_img',
            field=models.ImageField(default='course_img/default.png', upload_to='course_img', verbose_name='封面图片'),
        ),
        migrations.AlterField(
            model_name='course',
            name='course_name',
            field=models.CharField(max_length=32, null=True, verbose_name='课程名称'),
        ),
        migrations.AlterField(
            model_name='course',
            name='course_price',
            field=models.CharField(max_length=32, null=True, verbose_name='课程价格'),
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teacher_name', models.CharField(max_length=32, null=True, verbose_name='姓名')),
                ('teacher_motto', models.CharField(max_length=64, null=True, verbose_name='简介')),
                ('college', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='exam.College', verbose_name='学院')),
            ],
            options={
                'verbose_name': '教师表',
                'verbose_name_plural': '教师表',
                'db_table': 'study_teacher',
            },
        ),
        migrations.CreateModel(
            name='CourseChapter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chapter_name', models.CharField(max_length=32, null=True, verbose_name='章节名称')),
                ('chapter_link', models.CharField(max_length=64, null=True, verbose_name='章节链接')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exam.Course')),
            ],
            options={
                'verbose_name': '章节表',
                'verbose_name_plural': '章节表',
                'db_table': 'study_course_chapter',
            },
        ),
        migrations.AddField(
            model_name='course',
            name='teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='exam.Teacher', verbose_name='授课老师'),
        ),
    ]
