# Generated by Django 2.2.2 on 2021-08-12 19:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0009_auto_20210812_1920'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='teacher',
        ),
        migrations.AddField(
            model_name='teacher',
            name='course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='exam.Course'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='college',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='exam.College'),
        ),
    ]
