# Generated by Django 2.2.2 on 2021-08-13 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0016_auto_20210813_1451'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursechapter',
            name='chapter_link',
            field=models.CharField(max_length=255, null=True, verbose_name='章节链接'),
        ),
    ]
