# Generated by Django 2.2.2 on 2021-08-14 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0017_auto_20210813_2343'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursechapter',
            name='chapter_time',
            field=models.CharField(max_length=64, null=True, verbose_name='章节时长'),
        ),
    ]
