# Generated by Django 2.2.2 on 2021-08-15 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0019_auto_20210815_1240'),
    ]

    operations = [
        migrations.AddField(
            model_name='movies',
            name='movie_img',
            field=models.ImageField(null=True, upload_to='movies', verbose_name='电影封面'),
        ),
    ]
