# Generated by Django 2.2.2 on 2021-08-15 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0020_movies_movie_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movies',
            name='movie_img',
            field=models.CharField(max_length=32, null=True, verbose_name='电影封面'),
        ),
    ]
