# Generated by Django 2.2.2 on 2021-08-16 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0021_auto_20210815_1345'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='邮箱'),
        ),
        migrations.AlterField(
            model_name='user',
            name='real_name',
            field=models.CharField(max_length=32, null=True, unique=True, verbose_name='真实姓名'),
        ),
    ]
