# Generated by Django 2.2.2 on 2021-08-16 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0023_auto_20210816_0827'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=64, verbose_name='密码'),
        ),
    ]
