# Generated by Django 2.2.2 on 2021-08-16 08:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0028_auto_20210816_0837'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='user',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='user',
            name='email',
        ),
        migrations.RemoveField(
            model_name='user',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='user',
            name='real_name',
        ),
    ]
