# Generated by Django 2.2.2 on 2021-08-16 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0031_auto_20210816_1201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, null=True, verbose_name='邮箱'),
        ),
    ]
