# Generated by Django 2.2.2 on 2021-08-16 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0033_auto_20210816_1444'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='real_name',
            field=models.CharField(max_length=32, null=True, verbose_name='真实姓名'),
        ),
    ]
