# Generated by Django 2.2.2 on 2021-08-16 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0034_auto_20210816_1521'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='real_name',
            field=models.CharField(default='zs', max_length=32, verbose_name='真实姓名'),
        ),
    ]
