# Generated by Django 2.2.2 on 2021-08-10 19:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0004_auto_20210810_1624'),
    ]

    operations = [
        migrations.AddField(
            model_name='simple_question',
            name='task_score',
            field=models.CharField(max_length=32, null=True, verbose_name='任务分值'),
        ),
        migrations.AddField(
            model_name='task_record',
            name='que_answer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='exam.Simple_Question'),
        ),
    ]
