# Generated by Django 2.2.2 on 2021-08-10 19:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0005_auto_20210810_1902'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task_record',
            name='que_answer',
        ),
    ]
