# Generated by Django 2.2.2 on 2021-08-10 22:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0006_remove_task_record_que_answer'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_paper_answer',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='exam.User'),
        ),
        migrations.AlterField(
            model_name='paper_record',
            name='paper',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='exam.Paper', verbose_name='试卷类型'),
        ),
        migrations.AlterField(
            model_name='paper_record',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='exam.User', verbose_name='提交用户'),
        ),
    ]
