# Generated by Django 2.2.2 on 2021-08-12 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0010_auto_20210812_1930'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='course_user',
            field=models.ManyToManyField(null=True, to='exam.User'),
        ),
    ]
