# Generated by Django 2.2.2 on 2021-08-16 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0029_auto_20210816_0838'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, null=True, unique=True, verbose_name='邮箱'),
        ),
        migrations.AddField(
            model_name='user',
            name='phone',
            field=models.CharField(default=2, max_length=32, unique=True, verbose_name='手机'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='real_name',
            field=models.CharField(max_length=32, null=True, unique=True, verbose_name='真实姓名'),
        ),
    ]
