# Generated by Django 2.2.2 on 2021-08-16 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0030_auto_20210816_0839'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='邮箱'),
        ),
        migrations.AlterField(
            model_name='user',
            name='real_name',
            field=models.CharField(default='张三', max_length=32, verbose_name='真实姓名'),
        ),
        migrations.AlterUniqueTogether(
            name='user',
            unique_together={('username', 'phone', 'email')},
        ),
    ]
